apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-tolerations
spec:
  tolerations:
  - key: "example-key"
    operator: "Equal"
    value: "example-value"
    effect: "NoSchedule"
  containers:
  - name: example-container
    image: nginx:latest