apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-ci
rules:
 - apiGroups: ["*"]
   resources: ["*"]
   verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-ci
subjects:
- kind: ServiceAccount
  name: jenkins-ci
  namespace: $jenkins_namespace